server:
  port: 9090

spring:
  application:
    name: nacos-order-consumer
# Nacos的注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# order将要去访问的微服务名
service-url:
  nacos-user-service: http://nacos-provider
