server:
  port: 80 # 用户不需要写端口号访问

spring:
  application:
    name: cloud-payment-order
 # 添加Sleuth的配置
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: order-eureka
    prefer-ip-address: true

