server:
  port: 9001

spring:
  application:
    name: nacos-provider
# Nacos的注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.45.128:2222
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
