server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                  # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver                  # mysql驱动包
    url: jdbc:mysql:///cloud?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hz.entities          # 所有Entity别名类所在的包路径

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    instance-id: paymentHystrix8001
    prefer-ip-address: true
    # 设置client发送心跳包的时间间隔(默认30s)
    lease-renewal-interval-in-seconds: 30
    # EurekaServer收到最后一次心跳包之后的等待时间，默认90s
    lease-expiration-duration-in-seconds: 90