server:
  port: 80
# 注册到Consul服务器的订单微服务端口号

spring:
  application:
    name: cloud-order-consul80

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver                  # mysql驱动包
    url: jdbc:mysql:///cloud?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  # Consul server注册地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}


