server:
  port: 80
# 注册到Consul服务器的订单微服务端口号

spring:
  application:
    name: cloud-order-openFeign80

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver                  # mysql驱动包
    url: jdbc:mysql:///cloud?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka
# 设置Feign客户端超时时间 OpenFeign默认支持Ribbon
ribbon:
  ReadTimeout: 5000      # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用时间
  ConnectTimeoue: 5000  # 建立连接后从服务器读取到可用资源所用的时间
# Feign日志以什么级别去监控接口
logging:
  level:
    com.hz.openfeign.service.PaymentFeignService: debug




