server:
  port: 9002

spring:
  application:
    name: nacos-provider
  # Nacos的注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
