server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  # Gateway配置网关路由的yaml方式
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能 利用微服务名进行路由转发
      routes:
        - id: payment-route1         # 路由id 没有固定规则 但需要唯一
          # uri: http://localhost:8001 # 对应哪个微服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   # 断言，路径相匹配的进行路由

        - id: payment-route2
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            - After=2022-05-04T22:12:57.768+08:00[Asia/Shanghai]
            - Before=2023-05-04T22:12:57.768+08:00[Asia/Shanghai]
         # http://localhost:9527/payment/get/1007 --cookie="username=huzhen" 才能访问
         #   - Cookie=username,huzhen
         # 请求头必须包含X-Request-Id属性并且value为整数的正则表达式 -H "X-Request-Id:100"
         #   - Header=X-Request-Id, \d+
            - Method=GET,POST
#          filters:
#            - AddRequestHeader=X-Request-red, blue

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: cloud-gateway-service

